-- COO (Chief Operating Officer) Priority Engine Tables
-- Migration: 2026-01-20
-- Description: Add tables for COO priority engine, focus sessions, and preferences

-- ============================================================================
-- COO Priorities - Daily priorities generated by the COO AI
-- ============================================================================
CREATE TABLE IF NOT EXISTS coo_priorities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  priorities JSONB NOT NULL DEFAULT '[]',
  -- Each priority: {rank, taskId, source, title, reasoning, effort, status, guruContext}
  model_used VARCHAR(50), -- 'opus' or 'gemini'
  knowledge_context JSONB, -- Guru knowledge used for this generation
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  accepted_at TIMESTAMPTZ,
  modified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- ============================================================================
-- COO Focus Sessions - Track time spent on priorities
-- ============================================================================
CREATE TABLE IF NOT EXISTS coo_focus_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  priority_id UUID REFERENCES coo_priorities(id) ON DELETE SET NULL,
  priority_rank INTEGER, -- Which priority (1, 2, 3)
  task_id VARCHAR(255), -- ClickUp task ID or internal task ID
  task_title VARCHAR(500) NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paused_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  total_duration_minutes INTEGER DEFAULT 0,
  outcome VARCHAR(20) CHECK (outcome IN ('completed', 'paused', 'deferred', 'abandoned')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- COO Preferences - User settings for the COO
-- ============================================================================
CREATE TABLE IF NOT EXISTS coo_preferences (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  morning_briefing_time TIME DEFAULT '08:00',
  evening_summary_time TIME DEFAULT '18:00',
  max_priorities INTEGER DEFAULT 3 CHECK (max_priorities >= 1 AND max_priorities <= 10),
  push_intensity VARCHAR(20) DEFAULT 'medium' CHECK (push_intensity IN ('gentle', 'medium', 'aggressive')),
  preferred_model VARCHAR(20) DEFAULT 'opus' CHECK (preferred_model IN ('opus', 'gemini', 'both')),
  timezone VARCHAR(50) DEFAULT 'America/Chicago',
  briefing_enabled BOOLEAN DEFAULT true,
  accountability_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- COO Accountability Log - Track deferrals and completion patterns
-- ============================================================================
CREATE TABLE IF NOT EXISTS coo_accountability_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type VARCHAR(50) NOT NULL CHECK (event_type IN (
    'priority_accepted', 'priority_modified', 'priority_completed',
    'priority_deferred', 'focus_started', 'focus_paused', 
    'focus_completed', 'checkin_sent', 'checkin_acknowledged'
  )),
  priority_id UUID REFERENCES coo_priorities(id) ON DELETE SET NULL,
  session_id UUID REFERENCES coo_focus_sessions(id) ON DELETE SET NULL,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- Indexes
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_coo_priorities_user_date ON coo_priorities(user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_coo_priorities_date ON coo_priorities(date DESC);
CREATE INDEX IF NOT EXISTS idx_coo_focus_sessions_user ON coo_focus_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_coo_focus_sessions_priority ON coo_focus_sessions(priority_id);
CREATE INDEX IF NOT EXISTS idx_coo_focus_sessions_started ON coo_focus_sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_coo_accountability_user ON coo_accountability_log(user_id);
CREATE INDEX IF NOT EXISTS idx_coo_accountability_created ON coo_accountability_log(created_at DESC);

-- ============================================================================
-- Row Level Security
-- ============================================================================
ALTER TABLE coo_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE coo_focus_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE coo_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE coo_accountability_log ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Users can manage own coo priorities" ON coo_priorities;
CREATE POLICY "Users can manage own coo priorities" ON coo_priorities 
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own coo focus sessions" ON coo_focus_sessions;
CREATE POLICY "Users can manage own coo focus sessions" ON coo_focus_sessions 
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own coo preferences" ON coo_preferences;
CREATE POLICY "Users can manage own coo preferences" ON coo_preferences 
  FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage own coo accountability" ON coo_accountability_log;
CREATE POLICY "Users can manage own coo accountability" ON coo_accountability_log 
  FOR ALL USING (auth.uid() = user_id);

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================
DROP TRIGGER IF EXISTS update_coo_preferences_updated_at ON coo_preferences;
CREATE TRIGGER update_coo_preferences_updated_at
  BEFORE UPDATE ON coo_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
