#!/bin/bash

# Syndication Superstars Course Downloader
# Usage: ./download-all.sh "YOUR_KJB_SESSION_COOKIE_VALUE"

COOKIE="$1"
DEST="/Users/obi/Projects/RunAlNur/RunAlNur/syndication-resources/downloads"

if [ -z "$COOKIE" ]; then
    echo "❌ Usage: ./download-all.sh 'YOUR_KJB_SESSION_COOKIE_VALUE'"
    echo ""
    echo "To get your cookie:"
    echo "1. Go to https://training.syndicationsuperstars.com while logged in"
    echo "2. Open DevTools (Cmd+Option+I)"
    echo "3. Go to Application tab > Cookies"
    echo "4. Find '_kjb_session' and copy its Value"
    exit 1
fi

mkdir -p "$DEST"
cd "$DEST"

echo "🚀 Starting download of 114 files..."
echo "📁 Saving to: $DEST"
echo ""

# Download function
download() {
    local url="$1"
    local name="$2"
    
    if [ -f "$name" ]; then
        echo "⏭️  Skip (exists): $name"
        return
    fi
    
    echo "⬇️  Downloading: $name"
    curl -sL -b "_kjb_session=$COOKIE" -o "$name" "$url"
    
    if [ $? -eq 0 ] && [ -s "$name" ]; then
        echo "✅ $name"
    else
        echo "❌ Failed: $name"
        rm -f "$name" 2>/dev/null
    fi
}

# All 114 files
download "https://training.syndicationsuperstars.com/courses/downloads/2157983237/quick_analysis-xlsx" "Quick_Analysis.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157983238/quick_template_v2-xlsx" "Quick_Template_v2.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157983240/template_v09_blank-xlsx" "Template_v09_Blank.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157983241/template_v09-xlsx" "Template_v09.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2158113081/mfa-free-v1-01-xlsx" "MFA_v1.01.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2158113084/mfa-underwriting-checklist-xlsx" "MFA_Underwriting_Checklist.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2158113072/mfa-market-analysis-xlsx" "MFA_Market_Analysis.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985838/sample_letter-docx" "Sample_Letter.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985840/sample_2-doc" "Sample_Letter_2.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985842/sample_3-doc" "Sample_Letter_3.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985843/sample_4-doc" "Sample_Letter_4.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157994077/sa26c0_1-doc" "Sample_Letter_5.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985942/loi_1-docx" "LOI_1.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985945/loi_2-docx" "LOI_2.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985946/loi_3-docx" "LOI_3.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985947/loi_4-docx" "LOI_4.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985950/master_lease_option_loi-pdf" "Master_Lease_Option_LOI.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985954/assign_2-doc" "Assignment_of_Contract_v2.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985955/assign_3-doc" "Assignment_of_Contract_v3.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985957/purcha_2-doc" "Purchase_Sale_Agreement_Option2.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985956/purcha_1-doc" "Purchase_Sale_Agreement_Long_Form.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985958/sales_1-doc" "Sales_Contract_Wrap_Around.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985959/sample_1-doc" "Sample_Purchase_Sale_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985960/sample_1-txt" "SAMPLES_ONLY_CONSULT_ATTORNEY.txt"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985961/single_1-doc" "Single_Family_Sales_Contract.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985962/standa_1-doc" "Standard_RE_Purchase_Sale_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985963/wholes_1-doc" "Wholesaling_Purchase_Sale_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985964/broker_phone_call_script_1-docx" "Broker_Phone_Call_Script_1.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985965/broker_phone_call_script_2-docx" "Broker_Phone_Call_Script_2.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985966/questions_to_ask_seller-docx" "Questions_To_Ask_Seller.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985967/seller_cold_call_script-docx" "Seller_Cold_Call_Script.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985985/reques_1-doc" "Requested_Documents_From_Seller.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985984/normalizing_expenses-xlsx" "Normalizing_Expenses.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985983/multif_2-doc" "Multifamily_Property_Checklist.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985982/mastering_mf_acquisitions-xlsx" "Mastering_MF_Acquisitions.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985981/investment_criteria_checklist-docx" "Investment_Criteria_Checklist.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985980/garden_villas_om-pdf" "Garden_Villas_OM.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985979/due_diligence_checklist-xlsx" "Due_Diligence_Checklist.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985978/due_diligence_checklist-docx" "Due_Diligence_Checklist.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985977/driving_for_dollars_template-xlsx" "Driving_for_Dollars_Template.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985976/basic_property_purchase_worksheet-docx" "Basic_Property_Purchase_Worksheet.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985975/apartm_2-doc" "Apartments_Initial_Seller_Conversation.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985974/apartm_1-pdf" "Apartments_Initial_Seller_Conversation.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985973/apartm_1-doc" "Apartment_Exterior_Inspection_Report.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985972/advanc_1-pdf" "Advanced_Multifamily_Property_Checklist.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985971/_cash_on_return_what_if_analysis-png" "Cash_On_Return_What_If_Analysis.png"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985989/sample_llc_operating_agreement-docx" "Sample_LLC_Operating_Agreement.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985988/master_lease_agreement_template-1-doc" "Master_Lease_Agreement_Template.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985987/confid_1-doc" "Confidentiality_Non_Circumvent_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985993/sample-apartment-appraisal-pdf" "Sample_Apartment_Appraisal.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985992/phase-1-example-pdf" "Phase_1_Example.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985991/explaining_seller_financing_script-docx" "Explaining_Seller_Financing_Script.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985990/bank_script-docx" "Bank_Script.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986004/theult_1-doc" "Ultimate_Goal_Setting_Worksheet.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986003/self_evaluation_checklist-docx" "Self_Evaluation_Checklist.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986001/quadrants-jpg" "Quadrants.jpg"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986000/maslow_s_hierarchy_of_needs-png" "Maslows_Hierarchy_Of_Needs.png"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985999/energy_audit-docx" "Energy_Audit.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985998/daily_work_schedule-pdf" "Daily_Work_Schedule.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157985997/90-year_human_life_in_months-png" "90_Year_Human_Life_In_Months.png"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986008/the_four_markets_to_invest_in-pdf" "The_Four_Markets_To_Invest_In.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986006/real_estate_market_analysis_v3-xlsx" "Real_Estate_Market_Analysis_v3.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986018/the_multifamily_investing_process-pdf" "The_Multifamily_Investing_Process.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986017/the_5-30_unit_strategy-pdf" "The_5-30_Unit_Strategy.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986016/master_the_lingo-pdf" "Master_the_Lingo.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986015/link_library-docx" "Link_Library.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986014/harborside_partners_investment_criteria-pdf" "Harborside_Partners_Investment_Criteria.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986013/class_a-d_breakdown-pdf" "Class_A-D_Breakdown.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986010/29_fatal_mistakes-pdf" "29_Fatal_Mistakes.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986038/update_1-doc" "Questions_Property_Management_Company.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986037/tenant_1-doc" "Tenant_Estoppel_Certificate.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986036/short_1-doc" "Notice_of_Unit_Inspection.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986035/sample_1-doc" "Sample_Property_Management_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986034/reside_1-doc" "Residential_Lease_Extension_Agreement.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986033/rental_1-pdf" "Rental_Application_Advanced.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986032/notice_4-doc" "Notice_to_Tenant_Vacate.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986031/notice_3-doc" "Notice_New_Property_Management.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986030/notice_2-doc" "Notice_of_Lease_Renewal.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986029/notice_1-doc" "Notice_Inspection_Intent_to_Enter.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986028/non_pa_1-doc" "Non_Payment_Eviction_Letter.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986027/move_i_1-doc" "Move_In_Move_Out_Checklist.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986026/mainte_1-doc" "Maintenance_Repair_Work_Order.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986024/lease_2-doc" "Lease_Renewal_with_Rental_Increase.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986023/lease_1-doc" "Lease_Agreement_SAMPLE.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986022/hud_le_1-pdf" "HUD_Lead_Based_Paint_Pamphlet.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986021/addend_1-doc" "Addendum_to_Lease_Modifying_Terms.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986050/vacanc_1-pdf" "Vacancy_Report.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986048/rentroll-pdf" "Rent_Roll.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986046/recapr_1-pdf" "Recap_Report.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986045/profit_1-pdf" "Profit_Loss_12_Month_Recap.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986044/openwo_1-pdf" "Open_Work_Orders.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986043/fiscal_1-pdf" "Fiscal_Year_Budget.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986042/detail_1-pdf" "Detailed_Delinquency_Report.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986041/cashfl_2-pdf" "Cash_Flow_Details.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986040/cashfl_1-pdf" "Cash_Flow_Comparison.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986039/budget_1-pdf" "Budget_Comparison.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986065/the_real_estate_syndication_process-pdf" "Real_Estate_Syndication_Process.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986064/syndication_legal_timeline-png" "Syndication_Legal_Timeline.png"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986063/questions_an_investor_should_ask_a_syndicator-pdf" "Questions_Investor_Ask_Syndicator.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986062/nuts_and_bolts_of_a_syndication-pdf" "Nuts_and_Bolts_of_Syndication.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986061/investor_suitability_questionnaire_-pdf" "Investor_Suitability_Questionnaire.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986060/how_to_structure_a_syndicate-pdf" "How_to_Structure_a_Syndicate.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986059/how_to_structure_a_real_estate_syndicate-jpg" "How_to_Structure_RE_Syndicate.jpg"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986058/gp_split_worksheet-xlsx" "GP_Split_Worksheet.xlsx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986056/fund_structure-png" "Fund_Structure.png"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986055/example_org_chart-pdf" "Example_Org_Chart.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986054/506_b_506_c-jpg" "506b_506c_Comparison.jpg"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986071/multif_1-pdf" "Multifamily_Networking_Checklist.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986070/listof_1-doc" "List_Team_Members_Checklist.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986069/fullli_1-pdf" "Full_List_Partnership_Questions.pdf"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986068/exampl_1-doc" "Example_Memorandum_of_Understanding.doc"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986075/database_manager_job_ad-1-docx" "Database_Manager_Job_Ad.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986074/database_manager_agreement-docx" "Database_Manager_Agreement.docx"
download "https://training.syndicationsuperstars.com/courses/downloads/2157986073/blank_invoice-docx" "Blank_Invoice.docx"

echo ""
echo "✅ Download complete!"
echo "📁 Files saved to: $DEST"
ls -la "$DEST" | head -20
echo "..."
echo "Total files: $(ls -1 "$DEST" | wc -l)"
